AllCops:
  DisabledByDefault: true
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "examples/**/*"
    - "site/**/*"
    - "test/fixtures/**/*"
    - "output/**/*"
    - "vendor/**/*"

Lint:
  Enabled: true

Security:
  Enabled: true
