#!/usr/bin/env ruby
require "json"
puts JSON.generate({
  "results" => [
    {
      "gem" => { "name" => "rack" },
      "advisory" => {
        "id" => "CVE-2099-0001",
        "title" => "Example vulnerability",
        "criticality" => "high",
        "url" => "https://example.test/advisory"
      }
    }
  ]
})
exit 1
