source "https://rubygems.org"

gem "rails", "~> 8.0"

group :development, :test do
  gem "rubocop"
  gem "rubocop-rails"
  gem "brakeman"
  gem "bundler-audit"
  gem "reek"
  gem "strong_migrations"
  gem "prosopite"
  gem "flog"
  gem "flay"
end
